# Generated by Django 5.0.6 on 2024-05-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=28)),
                ('jersey_no', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('country_name', models.CharField(max_length=80)),
                ('occupation', models.CharField(max_length=85)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('O', 'other')], default='m', max_length=1)),
                ('profile_image', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
