# Generated by Django 5.0.6 on 2024-05-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_sportmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportmodel',
            name='gender',
        ),
    ]
