# Generated by Django 5.0.6 on 2024-05-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sportmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmodel',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('O', 'other')], default='m', max_length=1),
        ),
    ]
