# Generated by Django 5.0.6 on 2024-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sportmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmodel',
            name='gender',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
